# Generated by Django 5.0.6 on 2025-04-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='draft_soap_note',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='final_soap_note',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
