name: Formatting & Linting Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npm run lint:check

      - name: Run Prettier
        run: npm run fmt:check
