# Generated by Django 5.0.6 on 2025-04-20 06:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('audio_processing_started', 'Audio Processing Started'), ('transcription_complete', 'Transcription Complete'), ('details_extracted', 'Details Extracted'), ('text_generated', 'Text Generated'), ('completed', 'Completed'), ('error', 'Error')], max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollings', to='visits.visit')),
            ],
        ),
    ]
